info:
  head: head
  body: body
management:

  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://47.93.32.79:3306/trying?useUnicode=true&characterEncoding=UTF-8
    username: trying
    password: 1qazXSW@
    driver-class-name:  com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy


#    #JPA Configuration:
#    spring.jpa.database=mysql
#    spring.jpa.show-sql=true
#    spring.jpa.generate-ddl=true  #是否自动生成ddl
#    spring.jpa.hibernate.ddl-auto=update   #生成ddl的方式
#    spring.jpa.hibernate.naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy  #选择的命名策略

server:
  port: 8888
